# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoData.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fProtoData.proto\"(\n\x07\x43ommand\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x97\x01\n\tDroneData\x12\x10\n\x08\x61ltitude\x18\x01 \x01(\x02\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x0f\n\x07voltage\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\r\n\x05state\x18\x06 \x01(\t\x12\x12\n\nvideo_port\x18\x07 \x01(\x05\x12\x10\n\x08\x64rone_id\x18\x08 \x01(\t\"a\n\tDataPoint\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\x05\"(\n\x0bMissionData\x12\x19\n\x05point\x18\x01 \x03(\x0b\x32\n.DataPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=19
  _globals['_COMMAND']._serialized_end=59
  _globals['_DRONEDATA']._serialized_start=62
  _globals['_DRONEDATA']._serialized_end=213
  _globals['_DATAPOINT']._serialized_start=215
  _globals['_DATAPOINT']._serialized_end=312
  _globals['_MISSIONDATA']._serialized_start=314
  _globals['_MISSIONDATA']._serialized_end=354
# @@protoc_insertion_point(module_scope)
